"""Canonical LeetCode-style method names for the bundled problem catalog."""

METHOD_BY_PROBLEM_ID = {
    'best-stock-profit': 'maxProfit',
    'binary-search': 'search',
    'character-replacement': 'characterReplacement',
    'climbing-stairs': 'climbStairs',
    'coin-change': 'coinChange',
    'combination-sum': 'combinationSum',
    'container-most-water': 'maxArea',
    'contains-duplicate': 'containsDuplicate',
    'counting-bits': 'countBits',
    'course-schedule': 'canFinish',
    'daily-temperatures': 'dailyTemperatures',
    'decode-ways': 'numDecodings',
    'evaluate-rpn': 'evalRPN',
    'first-last-position': 'searchRange',
    'first-unique-character': 'firstUniqChar',
    'flood-fill': 'floodFill',
    'generate-parentheses': 'generateParenthesis',
    'group-anagrams': 'groupAnagrams',
    'house-robber': 'rob',
    'insert-interval': 'insert',
    'intersection-unique': 'intersection',
    'koko-bananas': 'minEatingSpeed',
    'leetcode-10-regular-expression-matching': 'isMatch',
    'leetcode-100-same-tree': 'isSameTree',
    'leetcode-101-symmetric-tree': 'isSymmetric',
    'leetcode-1011-capacity-to-ship-packages-within-d-days': 'shipWithinDays',
    'leetcode-1015-smallest-integer-divisible-by-k': 'smallestRepunitDivByK',
    'leetcode-102-binary-tree-level-order-traversal': 'levelOrder',
    'leetcode-103-binary-tree-zigzag-level-order-traversal': 'zigzagLevelOrder',
    'leetcode-104-maximum-depth-of-binary-tree': 'maxDepth',
    'leetcode-1046-last-stone-weight': 'lastStoneWeight',
    'leetcode-1047-remove-all-adjacent-duplicates-in-string': 'removeDuplicates',
    'leetcode-1048-longest-string-chain': 'longestStrChain',
    'leetcode-105-construct-binary-tree-from-preorder-and-inorder-traversal': 'buildTree',
    'leetcode-106-construct-binary-tree-from-inorder-and-postorder-traversal': 'buildTree',
    'leetcode-1060-missing-element-in-sorted-array': 'missingElement',
    'leetcode-107-binary-tree-level-order-traversal-ii': 'levelOrderBottom',
    'leetcode-1071-greatest-common-divisor-of-strings': 'gcdOfStrings',
    'leetcode-108-convert-sorted-array-to-binary-search-tree': 'sortedArrayToBST',
    'leetcode-1087-brace-expansion': 'expand',
    'leetcode-109-convert-sorted-list-to-binary-search-tree': 'sortedListToBST',
    'leetcode-1091-shortest-path-in-binary-matrix': 'shortestPathBinaryMatrix',
    'leetcode-1094-car-pooling': 'carPooling',
    'leetcode-1095-find-in-mountain-array': 'findInMountainArray',
    'leetcode-110-balanced-binary-tree': 'isBalanced',
    'leetcode-1101-the-earliest-moment-when-everyone-become-friends': 'earliestAcq',
    'leetcode-1102-path-with-maximum-minimum-value': 'maximumMinimumPath',
    'leetcode-1105-filling-bookcase-shelves': 'minHeightShelves',
    'leetcode-111-minimum-depth-of-binary-tree': 'minDepth',
    'leetcode-1110-delete-nodes-and-return-forest': 'delNodes',
    'leetcode-112-path-sum': 'hasPathSum',
    'leetcode-1123-lowest-common-ancestor-of-deepest-leaves': 'lcaDeepestLeaves',
    'leetcode-113-path-sum-ii': 'pathSum',
    'leetcode-114-flatten-binary-tree-to-linked-list': 'flatten',
    'leetcode-1143-longest-common-subsequence': 'longestCommonSubsequence',
    'leetcode-1146-snapshot-array': 'set',
    'leetcode-115-distinct-subsequences': 'numDistinct',
    'leetcode-116-populating-next-right-pointers-in-each-node': 'connect',
    'leetcode-117-populating-next-right-pointers-in-each-node-ii': 'connect',
    'leetcode-118-pascals-triangle': 'generate',
    'leetcode-119-pascals-triangle-ii': 'getRow',
    'leetcode-1197-minimum-knight-moves': 'minKnightMoves',
    'leetcode-12-integer-to-roman': 'intToRoman',
    'leetcode-120-triangle': 'minimumTotal',
    'leetcode-1209-remove-all-adjacent-duplicates-in-string-ii': 'removeDuplicates',
    'leetcode-1213-intersection-of-three-sorted-arrays': 'arraysIntersection',
    'leetcode-1216-valid-palindrome-iii': 'isValidPalindrome',
    'leetcode-122-best-time-to-buy-and-sell-stock-ii': 'maxProfit',
    'leetcode-123-best-time-to-buy-and-sell-stock-iii': 'maxProfit',
    'leetcode-124-binary-tree-maximum-path-sum': 'maxPathSum',
    'leetcode-1240-tiling-a-rectangle-with-the-fewest-squares': 'tilingRectangle',
    'leetcode-1248-count-number-of-nice-subarrays': 'numberOfSubarrays',
    'leetcode-1249-minimum-remove-to-make-valid-parentheses': 'minRemoveToMakeValid',
    'leetcode-1254-number-of-closed-islands': 'closedIsland',
    'leetcode-126-word-ladder-ii': 'findLadders',
    'leetcode-1262-greatest-sum-divisible-by-three': 'maxSumDivThree',
    'leetcode-127-word-ladder': 'ladderLength',
    'leetcode-1275-find-winner-on-a-tic-tac-toe-game': 'tictactoe',
    'leetcode-128-longest-consecutive-sequence': 'longestConsecutive',
    'leetcode-129-sum-root-to-leaf-numbers': 'sumNumbers',
    'leetcode-1293-shortest-path-in-a-grid-with-obstacles-elimination': 'shortestPath',
    'leetcode-13-roman-to-integer': 'romanToInt',
    'leetcode-130-surrounded-regions': 'solve',
    'leetcode-131-palindrome-partitioning': 'partition',
    'leetcode-1315-sum-of-nodes-with-even-valued-grandparent': 'sumEvenGrandparent',
    'leetcode-1316-distinct-echo-substrings': 'distinctEchoSubstrings',
    'leetcode-132-palindrome-partitioning-ii': 'minCut',
    'leetcode-1325-delete-leaves-with-a-given-value': 'removeLeafNodes',
    'leetcode-133-clone-graph': 'cloneGraph',
    'leetcode-134-gas-station': 'canCompleteCircuit',
    'leetcode-1344-angle-between-hands-of-a-clock': 'angleClock',
    'leetcode-135-candy': 'candy',
    'leetcode-1352-product-of-the-last-k-numbers': 'add',
    'leetcode-137-single-number-ii': 'singleNumber',
    'leetcode-1376-time-needed-to-inform-all-employees': 'numOfMinutes',
    'leetcode-138-copy-list-with-random-pointer': 'copyRandomList',
    'leetcode-1387-sort-integers-by-the-power-value': 'getKth',
    'leetcode-1392-longest-happy-prefix': 'longestPrefix',
    'leetcode-14-longest-common-prefix': 'longestCommonPrefix',
    'leetcode-140-word-break-ii': 'wordBreak',
    'leetcode-141-linked-list-cycle': 'hasCycle',
    'leetcode-142-linked-list-cycle-ii': 'detectCycle',
    'leetcode-1424-diagonal-traverse-ii': 'findDiagonalOrder',
    'leetcode-143-reorder-list': 'reorderList',
    'leetcode-144-binary-tree-preorder-traversal': 'preorderTraversal',
    'leetcode-1443-minimum-time-to-collect-all-apples-in-a-tree': 'minTime',
    'leetcode-1448-count-good-nodes-in-binary-tree': 'goodNodes',
    'leetcode-145-binary-tree-postorder-traversal': 'postorderTraversal',
    'leetcode-146-lru-cache': 'put',
    'leetcode-1463-cherry-pickup-ii': 'cherryPickup',
    'leetcode-147-insertion-sort-list': 'insertionSortList',
    'leetcode-1472-design-browser-history': 'visit',
    'leetcode-148-sort-list': 'sortList',
    'leetcode-149-max-points-on-a-line': 'maxPoints',
    'leetcode-15-3sum': 'threeSum',
    'leetcode-1518-water-bottles': 'numWaterBottles',
    'leetcode-152-maximum-product-subarray': 'maxProduct',
    'leetcode-1526-minimum-number-of-increments-on-subarrays-to-form-a-target-array': 'minNumberOperations',
    'leetcode-153-find-minimum-in-rotated-sorted-array': 'findMin',
    'leetcode-1539-kth-missing-positive-number': 'findKthPositive',
    'leetcode-154-find-minimum-in-rotated-sorted-array-ii': 'findMin',
    'leetcode-155-min-stack': 'push',
    'leetcode-157-read-n-characters-given-read4': 'read',
    'leetcode-1570-dot-product-of-two-sparse-vectors': 'dotProduct',
    'leetcode-1584-min-cost-to-connect-all-points': 'minCostConnectPoints',
    'leetcode-16-3sum-closest': 'threeSumClosest',
    'leetcode-160-intersection-of-two-linked-lists': 'getIntersectionNode',
    'leetcode-161-one-edit-distance': 'isOneEditDistance',
    'leetcode-162-find-peak-element': 'findPeakElement',
    'leetcode-163-missing-ranges': 'findMissingRanges',
    'leetcode-164-maximum-gap': 'maximumGap',
    'leetcode-1644-lowest-common-ancestor-of-a-binary-tree-ii': 'lowestCommonAncestor',
    'leetcode-165-compare-version-numbers': 'compareVersion',
    'leetcode-1650-lowest-common-ancestor-of-a-binary-tree-iii': 'lowestCommonAncestor',
    'leetcode-166-fraction-to-recurring-decimal': 'fractionToDecimal',
    'leetcode-167-two-sum-ii-input-array-is-sorted': 'twoSum',
    'leetcode-168-excel-sheet-column-title': 'convertToTitle',
    'leetcode-17-letter-combinations-of-a-phone-number': 'letterCombinations',
    'leetcode-171-excel-sheet-column-number': 'titleToNumber',
    'leetcode-172-factorial-trailing-zeroes': 'trailingZeroes',
    'leetcode-173-binary-search-tree-iterator': 'next',
    'leetcode-174-dungeon-game': 'calculateMinimumHP',
    'leetcode-1762-buildings-with-an-ocean-view': 'findBuildings',
    'leetcode-179-largest-number': 'largestNumber',
    'leetcode-18-4sum': 'fourSum',
    'leetcode-1834-single-threaded-cpu': 'getOrder',
    'leetcode-1851-minimum-interval-to-include-each-query': 'minInterval',
    'leetcode-187-repeated-dna-sequences': 'findRepeatedDnaSequences',
    'leetcode-188-best-time-to-buy-and-sell-stock-iv': 'maxProfit',
    'leetcode-189-rotate-array': 'rotate',
    'leetcode-1891-cutting-ribbons': 'maxLength',
    'leetcode-1899-merge-triplets-to-form-target-triplet': 'mergeTriplets',
    'leetcode-19-remove-nth-node-from-end-of-list': 'removeNthFromEnd',
    'leetcode-190-reverse-bits': 'reverseBits',
    'leetcode-1901-find-a-peak-element-ii': 'findPeakGrid',
    'leetcode-191-number-of-1-bits': 'hammingWeight',
    'leetcode-1944-number-of-visible-people-in-a-queue': 'canSeePersonsCount',
    'leetcode-199-binary-tree-right-side-view': 'rightSideView',
    'leetcode-2-add-two-numbers': 'addTwoNumbers',
    'leetcode-2000-reverse-prefix-of-word': 'reversePrefix',
    'leetcode-201-bitwise-and-of-numbers-range': 'rangeBitwiseAnd',
    'leetcode-2013-detect-squares': 'add',
    'leetcode-202-happy-number': 'isHappy',
    'leetcode-203-remove-linked-list-elements': 'removeElements',
    'leetcode-204-count-primes': 'countPrimes',
    'leetcode-2048-next-greater-numerically-balanced-number': 'nextBeautifulNumber',
    'leetcode-205-isomorphic-strings': 'isIsomorphic',
    'leetcode-206-reverse-linked-list': 'reverseList',
    'leetcode-2065-maximum-path-quality-of-a-graph': 'maximalPathQuality',
    'leetcode-208-implement-trie-prefix-tree': 'insert',
    'leetcode-21-merge-two-sorted-lists': 'mergeTwoLists',
    'leetcode-210-course-schedule-ii': 'findOrder',
    'leetcode-2104-sum-of-subarray-ranges': 'subArrayRanges',
    'leetcode-211-design-add-and-search-words-data-structure': 'addWord',
    'leetcode-213-house-robber-ii': 'rob',
    'leetcode-214-shortest-palindrome': 'shortestPalindrome',
    'leetcode-215-kth-largest-element-in-an-array': 'findKthLargest',
    'leetcode-2164-sort-even-and-odd-indices-independently': 'sortEvenOdd',
    'leetcode-218-the-skyline-problem': 'getSkyline',
    'leetcode-219-contains-duplicate-ii': 'containsNearbyDuplicate',
    'leetcode-2203-minimum-weighted-subgraph-with-the-required-paths': 'minimumWeight',
    'leetcode-221-maximal-square': 'maximalSquare',
    'leetcode-222-count-complete-tree-nodes': 'countNodes',
    'leetcode-223-rectangle-area': 'computeArea',
    'leetcode-224-basic-calculator': 'calculate',
    'leetcode-225-implement-stack-using-queues': 'push',
    'leetcode-2257-count-unguarded-cells-in-the-grid': 'countUnguarded',
    'leetcode-226-invert-binary-tree': 'invertTree',
    'leetcode-2265-count-nodes-equal-to-average-of-subtree': 'averageOfSubtree',
    'leetcode-227-basic-calculator-ii': 'calculate',
    'leetcode-228-summary-ranges': 'summaryRanges',
    'leetcode-2290-minimum-obstacle-removal-to-reach-corner': 'minimumObstacles',
    'leetcode-2291-maximum-profit-from-trading-stocks': 'maximumProfit',
    'leetcode-23-merge-k-sorted-lists': 'mergeKLists',
    'leetcode-230-kth-smallest-element-in-a-bst': 'kthSmallest',
    'leetcode-2302-count-subarrays-with-score-less-than-k': 'countSubarrays',
    'leetcode-231-power-of-two': 'isPowerOfTwo',
    'leetcode-232-implement-queue-using-stacks': 'push',
    'leetcode-234-palindrome-linked-list': 'isPalindrome',
    'leetcode-235-lowest-common-ancestor-of-a-binary-search-tree': 'lowestCommonAncestor',
    'leetcode-236-lowest-common-ancestor-of-a-binary-tree': 'lowestCommonAncestor',
    'leetcode-239-sliding-window-maximum': 'maxSlidingWindow',
    'leetcode-24-swap-nodes-in-pairs': 'swapPairs',
    'leetcode-240-search-a-2d-matrix-ii': 'searchMatrix',
    'leetcode-246-strobogrammatic-number': 'isStrobogrammatic',
    'leetcode-249-group-shifted-strings': 'groupStrings',
    'leetcode-25-reverse-nodes-in-k-group': 'reverseKGroup',
    'leetcode-251-flatten-2d-vector': 'next',
    'leetcode-252-meeting-rooms': 'canAttendMeetings',
    'leetcode-253-meeting-rooms-ii': 'minMeetingRooms',
    'leetcode-254-factor-combinations': 'getFactors',
    'leetcode-256-paint-house': 'minCost',
    'leetcode-258-add-digits': 'addDigits',
    'leetcode-259-3sum-smaller': 'threeSumSmaller',
    'leetcode-2591-distribute-money-to-maximum-children': 'distMoney',
    'leetcode-26-remove-duplicates-from-sorted-array': 'removeDuplicates',
    'leetcode-261-graph-valid-tree': 'validTree',
    'leetcode-263-ugly-number': 'isUgly',
    'leetcode-265-paint-house-ii': 'minCostII',
    'leetcode-2654-minimum-number-of-operations-to-make-all-array-elements-equal-to-1': 'minOperations',
    'leetcode-267-palindrome-permutation-ii': 'generatePalindromes',
    'leetcode-269-alien-dictionary': 'alienOrder',
    'leetcode-27-remove-element': 'removeElement',
    'leetcode-270-closest-binary-search-tree-value': 'closestValue',
    'leetcode-271-encode-and-decode-strings': 'encode',
    'leetcode-273-integer-to-english-words': 'numberToWords',
    'leetcode-274-h-index': 'hIndex',
    'leetcode-275-h-index-ii': 'hIndex',
    'leetcode-277-find-the-celebrity': 'findCelebrity',
    'leetcode-279-perfect-squares': 'numSquares',
    'leetcode-28-find-the-index-of-the-first-occurrence-in-a-string': 'strStr',
    'leetcode-2812-find-the-safest-path-in-a-grid': 'maximumSafenessFactor',
    'leetcode-284-peeking-iterator': 'next',
    'leetcode-285-inorder-successor-in-bst': 'inorderSuccessor',
    'leetcode-286-walls-and-gates': 'wallsAndGates',
    'leetcode-287-find-the-duplicate-number': 'findDuplicate',
    'leetcode-29-divide-two-integers': 'divide',
    'leetcode-290-word-pattern': 'wordPattern',
    'leetcode-292-nim-game': 'canWinNim',
    'leetcode-295-find-median-from-data-stream': 'addNum',
    'leetcode-2962-count-subarrays-where-max-element-appears-at-least-k-times': 'countSubarrays',
    'leetcode-297-serialize-and-deserialize-binary-tree': 'serialize',
    'leetcode-30-substring-with-concatenation-of-all-words': 'findSubstring',
    'leetcode-301-remove-invalid-parentheses': 'removeInvalidParentheses',
    'leetcode-303-range-sum-query-immutable': 'sumRange',
    'leetcode-309-best-time-to-buy-and-sell-stock-with-cooldown': 'maxProfit',
    'leetcode-3090-maximum-length-substring-with-two-occurrences': 'maximumLengthSubstring',
    'leetcode-31-next-permutation': 'nextPermutation',
    'leetcode-311-sparse-matrix-multiplication': 'multiply',
    'leetcode-312-burst-balloons': 'maxCoins',
    'leetcode-314-binary-tree-vertical-order-traversal': 'verticalOrder',
    'leetcode-317-shortest-distance-from-all-buildings': 'shortestDistance',
    'leetcode-32-longest-valid-parentheses': 'longestValidParentheses',
    'leetcode-3211-generate-binary-strings-without-adjacent-zeros': 'validStrings',
    'leetcode-323-number-of-connected-components-in-an-undirected-graph': 'countComponents',
    'leetcode-325-maximum-size-subarray-sum-equals-k': 'maxSubArrayLen',
    'leetcode-328-odd-even-linked-list': 'oddEvenList',
    'leetcode-329-longest-increasing-path-in-a-matrix': 'longestIncreasingPath',
    'leetcode-332-reconstruct-itinerary': 'findItinerary',
    'leetcode-3349-adjacent-increasing-subarrays-detection-i': 'hasIncreasingSubarrays',
    'leetcode-3350-adjacent-increasing-subarrays-detection-ii': 'maxIncreasingSubarrays',
    'leetcode-339-nested-list-weight-sum': 'depthSum',
    'leetcode-34-find-first-and-last-position-of-element-in-sorted-array': 'searchRange',
    'leetcode-340-longest-substring-with-at-most-k-distinct-characters': 'lengthOfLongestSubstringKDistinct',
    'leetcode-3407-substring-matching-pattern': 'hasMatch',
    'leetcode-341-flatten-nested-list-iterator': 'next',
    'leetcode-3411-maximum-subarray-with-equal-products': 'maxLength',
    'leetcode-343-integer-break': 'integerBreak',
    'leetcode-3446-sort-matrix-by-diagonals': 'sortMatrix',
    'leetcode-345-reverse-vowels-of-a-string': 'reverseVowels',
    'leetcode-3461-check-if-digits-are-equal-in-string-after-operations-i': 'hasSameDigits',
    'leetcode-348-design-tic-tac-toe': 'move',
    'leetcode-3481-apply-substitutions': 'applySubstitutions',
    'leetcode-35-search-insert-position': 'searchInsert',
    'leetcode-3507-minimum-pair-removal-to-sort-array-i': 'minimumPairRemoval',
    'leetcode-3527-find-the-most-common-response': 'findCommonResponse',
    'leetcode-354-russian-doll-envelopes': 'maxEnvelopes',
    'leetcode-3545-minimum-deletions-for-at-most-k-distinct-characters': 'minDeletion',
    'leetcode-355-design-twitter': 'postTweet',
    'leetcode-36-valid-sudoku': 'isValidSudoku',
    'leetcode-3613-minimize-maximum-component-cost': 'minCost',
    'leetcode-362-design-hit-counter': 'hit',
    'leetcode-366-find-leaves-of-binary-tree': 'findLeaves',
    'leetcode-367-valid-perfect-square': 'isPerfectSquare',
    'leetcode-368-largest-divisible-subset': 'largestDivisibleSubset',
    'leetcode-37-sudoku-solver': 'solveSudoku',
    'leetcode-371-sum-of-two-integers': 'getSum',
    'leetcode-377-combination-sum-iv': 'combinationSum4',
    'leetcode-378-kth-smallest-element-in-a-sorted-matrix': 'kthSmallest',
    'leetcode-38-count-and-say': 'countAndSay',
    'leetcode-380-insert-delete-getrandom-o1': 'insert',
    'leetcode-385-mini-parser': 'deserialize',
    'leetcode-388-longest-absolute-file-path': 'lengthLongestPath',
    'leetcode-392-is-subsequence': 'isSubsequence',
    'leetcode-394-decode-string': 'decodeString',
    'leetcode-398-random-pick-index': 'pick',
    'leetcode-399-evaluate-division': 'calcEquation',
    'leetcode-4-median-of-two-sorted-arrays': 'findMedianSortedArrays',
    'leetcode-40-combination-sum-ii': 'combinationSum2',
    'leetcode-402-remove-k-digits': 'removeKdigits',
    'leetcode-406-queue-reconstruction-by-height': 'reconstructQueue',
    'leetcode-408-valid-word-abbreviation': 'validWordAbbreviation',
    'leetcode-41-first-missing-positive': 'firstMissingPositive',
    'leetcode-410-split-array-largest-sum': 'splitArray',
    'leetcode-415-add-strings': 'addStrings',
    'leetcode-416-partition-equal-subset-sum': 'canPartition',
    'leetcode-417-pacific-atlantic-water-flow': 'pacificAtlantic',
    'leetcode-42-trapping-rain-water': 'trap',
    'leetcode-426-convert-binary-search-tree-to-sorted-doubly-linked-list': 'treeToDoublyList',
    'leetcode-428-serialize-and-deserialize-n-ary-tree': 'serialize',
    'leetcode-43-multiply-strings': 'multiply',
    'leetcode-430-flatten-a-multilevel-doubly-linked-list': 'flatten',
    'leetcode-433-minimum-genetic-mutation': 'minMutation',
    'leetcode-435-non-overlapping-intervals': 'eraseOverlapIntervals',
    'leetcode-437-path-sum-iii': 'pathSum',
    'leetcode-44-wildcard-matching': 'isMatch',
    'leetcode-443-string-compression': 'compress',
    'leetcode-448-find-all-numbers-disappeared-in-an-array': 'findDisappearedNumbers',
    'leetcode-45-jump-game-ii': 'jump',
    'leetcode-456-132-pattern': 'find132pattern',
    'leetcode-459-repeated-substring-pattern': 'repeatedSubstringPattern',
    'leetcode-460-lfu-cache': 'put',
    'leetcode-463-island-perimeter': 'islandPerimeter',
    'leetcode-468-validate-ip-address': 'validIPAddress',
    'leetcode-47-permutations-ii': 'permuteUnique',
    'leetcode-474-ones-and-zeroes': 'findMaxForm',
    'leetcode-48-rotate-image': 'rotate',
    'leetcode-480-sliding-window-median': 'medianSlidingWindow',
    'leetcode-489-robot-room-cleaner': 'cleanRoom',
    'leetcode-494-target-sum': 'findTargetSumWays',
    'leetcode-496-next-greater-element-i': 'nextGreaterElement',
    'leetcode-498-diagonal-traverse': 'findDiagonalOrder',
    'leetcode-5-longest-palindromic-substring': 'longestPalindrome',
    'leetcode-50-powx-n': 'myPow',
    'leetcode-503-next-greater-element-ii': 'nextGreaterElements',
    'leetcode-51-n-queens': 'solveNQueens',
    'leetcode-510-inorder-successor-in-bst-ii': 'inorderSuccessor',
    'leetcode-518-coin-change-ii': 'change',
    'leetcode-52-n-queens-ii': 'totalNQueens',
    'leetcode-520-detect-capital': 'detectCapitalUse',
    'leetcode-523-continuous-subarray-sum': 'checkSubarraySum',
    'leetcode-525-contiguous-array': 'findMaxLength',
    'leetcode-528-random-pick-with-weight': 'pickIndex',
    'leetcode-532-k-diff-pairs-in-an-array': 'findPairs',
    'leetcode-536-construct-binary-tree-from-string': 'str2tree',
    'leetcode-540-single-element-in-a-sorted-array': 'singleNonDuplicate',
    'leetcode-541-reverse-string-ii': 'reverseStr',
    'leetcode-543-diameter-of-binary-tree': 'diameterOfBinaryTree',
    'leetcode-545-boundary-of-binary-tree': 'boundaryOfBinaryTree',
    'leetcode-55-jump-game': 'canJump',
    'leetcode-560-subarray-sum-equals-k': 'subarraySum',
    'leetcode-567-permutation-in-string': 'checkInclusion',
    'leetcode-572-subtree-of-another-tree': 'isSubtree',
    'leetcode-58-length-of-last-word': 'lengthOfLastWord',
    'leetcode-59-spiral-matrix-ii': 'generateMatrix',
    'leetcode-6-zigzag-conversion': 'convert',
    'leetcode-60-permutation-sequence': 'getPermutation',
    'leetcode-605-can-place-flowers': 'canPlaceFlowers',
    'leetcode-606-construct-string-from-binary-tree': 'tree2str',
    'leetcode-61-rotate-list': 'rotateRight',
    'leetcode-617-merge-two-binary-trees': 'mergeTrees',
    'leetcode-62-unique-paths': 'uniquePaths',
    'leetcode-621-task-scheduler': 'leastInterval',
    'leetcode-628-maximum-product-of-three-numbers': 'maximumProduct',
    'leetcode-63-unique-paths-ii': 'uniquePathsWithObstacles',
    'leetcode-630-course-schedule-iii': 'scheduleCourse',
    'leetcode-636-exclusive-time-of-functions': 'exclusiveTime',
    'leetcode-64-minimum-path-sum': 'minPathSum',
    'leetcode-643-maximum-average-subarray-i': 'findMaxAverage',
    'leetcode-645-set-mismatch': 'findErrorNums',
    'leetcode-647-palindromic-substrings': 'countSubstrings',
    'leetcode-65-valid-number': 'isNumber',
    'leetcode-652-find-duplicate-subtrees': 'findDuplicateSubtrees',
    'leetcode-658-find-k-closest-elements': 'findClosestElements',
    'leetcode-66-plus-one': 'plusOne',
    'leetcode-67-add-binary': 'addBinary',
    'leetcode-670-maximum-swap': 'maximumSwap',
    'leetcode-673-number-of-longest-increasing-subsequence': 'findNumberOfLIS',
    'leetcode-678-valid-parenthesis-string': 'checkValidString',
    'leetcode-68-text-justification': 'fullJustify',
    'leetcode-680-valid-palindrome-ii': 'validPalindrome',
    'leetcode-684-redundant-connection': 'findRedundantConnection',
    'leetcode-686-repeated-string-match': 'repeatedStringMatch',
    'leetcode-69-sqrtx': 'mySqrt',
    'leetcode-690-employee-importance': 'getImportance',
    'leetcode-693-binary-number-with-alternating-bits': 'hasAlternatingBits',
    'leetcode-695-max-area-of-island': 'maxAreaOfIsland',
    'leetcode-697-degree-of-an-array': 'findShortestSubArray',
    'leetcode-698-partition-to-k-equal-sum-subsets': 'canPartitionKSubsets',
    'leetcode-7-reverse-integer': 'reverse',
    'leetcode-703-kth-largest-element-in-a-stream': 'add',
    'leetcode-707-design-linked-list': 'addAtHead',
    'leetcode-708-insert-into-a-sorted-circular-linked-list': 'insert',
    'leetcode-71-simplify-path': 'simplifyPath',
    'leetcode-713-subarray-product-less-than-k': 'numSubarrayProductLessThanK',
    'leetcode-714-best-time-to-buy-and-sell-stock-with-transaction-fee': 'maxProfit',
    'leetcode-72-edit-distance': 'minDistance',
    'leetcode-720-longest-word-in-dictionary': 'longestWord',
    'leetcode-721-accounts-merge': 'accountsMerge',
    'leetcode-722-remove-comments': 'removeComments',
    'leetcode-724-find-pivot-index': 'pivotIndex',
    'leetcode-729-my-calendar-i': 'book',
    'leetcode-735-asteroid-collision': 'asteroidCollision',
    'leetcode-74-search-a-2d-matrix': 'searchMatrix',
    'leetcode-741-cherry-pickup': 'cherryPickup',
    'leetcode-743-network-delay-time': 'networkDelayTime',
    'leetcode-746-min-cost-climbing-stairs': 'minCostClimbingStairs',
    'leetcode-75-sort-colors': 'sortColors',
    'leetcode-76-minimum-window-substring': 'minWindow',
    'leetcode-763-partition-labels': 'partitionLabels',
    'leetcode-77-combinations': 'combine',
    'leetcode-772-basic-calculator-iii': 'calculate',
    'leetcode-778-swim-in-rising-water': 'swimInWater',
    'leetcode-784-letter-case-permutation': 'letterCasePermutation',
    'leetcode-787-cheapest-flights-within-k-stops': 'findCheapestPrice',
    'leetcode-79-word-search': 'exist',
    'leetcode-791-custom-sort-string': 'customSortString',
    'leetcode-796-rotate-string': 'rotateString',
    'leetcode-8-string-to-integer-atoi': 'myAtoi',
    'leetcode-80-remove-duplicates-from-sorted-array-ii': 'removeDuplicates',
    'leetcode-81-search-in-rotated-sorted-array-ii': 'search',
    'leetcode-82-remove-duplicates-from-sorted-list-ii': 'deleteDuplicates',
    'leetcode-820-short-encoding-of-words': 'minimumLengthEncoding',
    'leetcode-824-goat-latin': 'toGoatLatin',
    'leetcode-825-friends-of-appropriate-ages': 'numFriendRequests',
    'leetcode-827-making-a-large-island': 'largestIsland',
    'leetcode-83-remove-duplicates-from-sorted-list': 'deleteDuplicates',
    'leetcode-833-find-and-replace-in-string': 'findReplaceString',
    'leetcode-84-largest-rectangle-in-histogram': 'largestRectangleArea',
    'leetcode-846-hand-of-straights': 'isNStraightHand',
    'leetcode-849-maximize-distance-to-closest-person': 'maxDistToClosest',
    'leetcode-85-maximal-rectangle': 'maximalRectangle',
    'leetcode-853-car-fleet': 'carFleet',
    'leetcode-857-minimum-cost-to-hire-k-workers': 'mincostToHireWorkers',
    'leetcode-86-partition-list': 'partition',
    'leetcode-863-all-nodes-distance-k-in-binary-tree': 'distanceK',
    'leetcode-864-shortest-path-to-get-all-keys': 'shortestPathAllKeys',
    'leetcode-867-transpose-matrix': 'transpose',
    'leetcode-87-scramble-string': 'isScramble',
    'leetcode-872-leaf-similar-trees': 'leafSimilar',
    'leetcode-88-merge-sorted-array': 'merge',
    'leetcode-89-gray-code': 'grayCode',
    'leetcode-895-maximum-frequency-stack': 'push',
    'leetcode-9-palindrome-number': 'isPalindrome',
    'leetcode-90-subsets-ii': 'subsetsWithDup',
    'leetcode-907-sum-of-subarray-minimums': 'sumSubarrayMins',
    'leetcode-909-snakes-and-ladders': 'snakesAndLadders',
    'leetcode-918-maximum-sum-circular-subarray': 'maxSubarraySumCircular',
    'leetcode-92-reverse-linked-list-ii': 'reverseBetween',
    'leetcode-921-minimum-add-to-make-parentheses-valid': 'minAddToMakeValid',
    'leetcode-93-restore-ip-addresses': 'restoreIpAddresses',
    'leetcode-931-minimum-falling-path-sum': 'minFallingPathSum',
    'leetcode-934-shortest-bridge': 'shortestBridge',
    'leetcode-935-knight-dialer': 'knightDialer',
    'leetcode-938-range-sum-of-bst': 'rangeSumBST',
    'leetcode-94-binary-tree-inorder-traversal': 'inorderTraversal',
    'leetcode-95-unique-binary-search-trees-ii': 'generateTrees',
    'leetcode-958-check-completeness-of-a-binary-tree': 'isCompleteTree',
    'leetcode-96-unique-binary-search-trees': 'numTrees',
    'leetcode-966-vowel-spellchecker': 'spellchecker',
    'leetcode-97-interleaving-string': 'isInterleave',
    'leetcode-973-k-closest-points-to-origin': 'kClosest',
    'leetcode-976-largest-perimeter-triangle': 'largestPerimeter',
    'leetcode-977-squares-of-a-sorted-array': 'sortedSquares',
    'leetcode-98-validate-binary-search-tree': 'isValidBST',
    'leetcode-981-time-based-key-value-store': 'set',
    'leetcode-986-interval-list-intersections': 'intervalIntersection',
    'leetcode-987-vertical-order-traversal-of-a-binary-tree': 'verticalTraversal',
    'leetcode-989-add-to-array-form-of-integer': 'addToArrayForm',
    'leetcode-99-recover-binary-search-tree': 'recoverTree',
    'leetcode-994-rotting-oranges': 'orangesRotting',
    'leetcode-996-number-of-squareful-arrays': 'numSquarefulPerms',
    'longest-increasing-subsequence': 'lengthOfLIS',
    'longest-unique-substring': 'lengthOfLongestSubstring',
    'majority-element': 'majorityElement',
    'maximum-subarray': 'maxSubArray',
    'merge-intervals': 'merge',
    'merge-sorted-arrays': 'merge',
    'minimum-size-subarray-sum': 'minSubArrayLen',
    'missing-number': 'missingNumber',
    'move-zeroes': 'moveZeroes',
    'number-of-islands': 'numIslands',
    'permutations': 'permute',
    'product-except-self': 'productExceptSelf',
    'ransom-note': 'canConstruct',
    'reverse-words': 'reverseWords',
    'rotate-matrix': 'rotate',
    'search-rotated-array': 'search',
    'set-matrix-zeroes': 'setZeroes',
    'shortest-unweighted-path': 'shortestPath',
    'single-number': 'singleNumber',
    'spiral-matrix': 'spiralOrder',
    'subsets': 'subsets',
    'three-sum': 'threeSum',
    'top-k-frequent': 'topKFrequent',
    'two-sum': 'twoSum',
    'valid-anagram': 'isAnagram',
    'valid-palindrome': 'isPalindrome',
    'valid-parentheses': 'isValid',
    'word-break': 'wordBreak',
}

PARAMETERS_BY_PROBLEM_ID = {
    'best-stock-profit': ('prices',),
    'binary-search': ('nums', 'target'),
    'character-replacement': ('s', 'k'),
    'climbing-stairs': ('n',),
    'coin-change': ('coins', 'amount'),
    'combination-sum': ('candidates', 'target'),
    'container-most-water': ('height',),
    'contains-duplicate': ('nums',),
    'counting-bits': ('n',),
    'course-schedule': ('numCourses', 'prerequisites'),
    'daily-temperatures': ('temperatures',),
    'decode-ways': ('s',),
    'evaluate-rpn': ('tokens',),
    'first-last-position': ('nums', 'target'),
    'first-unique-character': ('s',),
    'flood-fill': ('image', 'sr', 'sc', 'color'),
    'generate-parentheses': ('n',),
    'group-anagrams': ('strs',),
    'house-robber': ('nums',),
    'insert-interval': ('intervals', 'newInterval'),
    'intersection-unique': ('nums1', 'nums2'),
    'koko-bananas': ('piles', 'h'),
    'leetcode-10-regular-expression-matching': ('s', 'p'),
    'leetcode-100-same-tree': ('p', 'q'),
    'leetcode-101-symmetric-tree': ('root',),
    'leetcode-1011-capacity-to-ship-packages-within-d-days': ('weights', 'days'),
    'leetcode-1015-smallest-integer-divisible-by-k': ('K',),
    'leetcode-102-binary-tree-level-order-traversal': ('root',),
    'leetcode-103-binary-tree-zigzag-level-order-traversal': ('root',),
    'leetcode-104-maximum-depth-of-binary-tree': ('root',),
    'leetcode-1047-remove-all-adjacent-duplicates-in-string': ('S',),
    'leetcode-1048-longest-string-chain': ('words',),
    'leetcode-105-construct-binary-tree-from-preorder-and-inorder-traversal': ('preorder', 'inorder'),
    'leetcode-106-construct-binary-tree-from-inorder-and-postorder-traversal': ('inorder', 'postorder'),
    'leetcode-1060-missing-element-in-sorted-array': ('nums', 'k'),
    'leetcode-107-binary-tree-level-order-traversal-ii': ('root',),
    'leetcode-1071-greatest-common-divisor-of-strings': ('str1', 'str2'),
    'leetcode-108-convert-sorted-array-to-binary-search-tree': ('nums',),
    'leetcode-1087-brace-expansion': ('s',),
    'leetcode-109-convert-sorted-list-to-binary-search-tree': ('head',),
    'leetcode-110-balanced-binary-tree': ('root',),
    'leetcode-111-minimum-depth-of-binary-tree': ('root',),
    'leetcode-112-path-sum': ('root', 'summ'),
    'leetcode-113-path-sum-ii': ('root', 'summ'),
    'leetcode-114-flatten-binary-tree-to-linked-list': ('root',),
    'leetcode-115-distinct-subsequences': ('s', 't'),
    'leetcode-116-populating-next-right-pointers-in-each-node': ('root',),
    'leetcode-117-populating-next-right-pointers-in-each-node-ii': ('root',),
    'leetcode-118-pascals-triangle': ('numRows',),
    'leetcode-119-pascals-triangle-ii': ('rowIndex',),
    'leetcode-12-integer-to-roman': ('num',),
    'leetcode-120-triangle': ('triangle',),
    'leetcode-122-best-time-to-buy-and-sell-stock-ii': ('prices',),
    'leetcode-123-best-time-to-buy-and-sell-stock-iii': ('prices',),
    'leetcode-124-binary-tree-maximum-path-sum': ('root',),
    'leetcode-126-word-ladder-ii': ('beginWord', 'endWord', 'wordList'),
    'leetcode-127-word-ladder': ('beginWord', 'endWord', 'wordList'),
    'leetcode-128-longest-consecutive-sequence': ('nums',),
    'leetcode-129-sum-root-to-leaf-numbers': ('root',),
    'leetcode-13-roman-to-integer': ('s',),
    'leetcode-130-surrounded-regions': ('board',),
    'leetcode-131-palindrome-partitioning': ('s',),
    'leetcode-132-palindrome-partitioning-ii': ('s',),
    'leetcode-133-clone-graph': ('node',),
    'leetcode-134-gas-station': ('gas', 'cost'),
    'leetcode-135-candy': ('ratings',),
    'leetcode-137-single-number-ii': ('nums',),
    'leetcode-138-copy-list-with-random-pointer': ('head',),
    'leetcode-14-longest-common-prefix': ('strs',),
    'leetcode-140-word-break-ii': ('s', 'wordDict'),
    'leetcode-143-reorder-list': ('head',),
    'leetcode-144-binary-tree-preorder-traversal': ('root',),
    'leetcode-145-binary-tree-postorder-traversal': ('root',),
    'leetcode-146-lru-cache': ('key', 'value'),
    'leetcode-147-insertion-sort-list': ('head',),
    'leetcode-148-sort-list': ('head',),
    'leetcode-149-max-points-on-a-line': ('points',),
    'leetcode-15-3sum': ('nums',),
    'leetcode-152-maximum-product-subarray': ('nums',),
    'leetcode-153-find-minimum-in-rotated-sorted-array': ('nums',),
    'leetcode-154-find-minimum-in-rotated-sorted-array-ii': ('nums',),
    'leetcode-157-read-n-characters-given-read4': ('buf', 'n'),
    'leetcode-16-3sum-closest': ('nums', 'target'),
    'leetcode-161-one-edit-distance': ('s', 't'),
    'leetcode-162-find-peak-element': ('nums',),
    'leetcode-163-missing-ranges': ('nums', 'lower', 'upper'),
    'leetcode-164-maximum-gap': ('nums',),
    'leetcode-165-compare-version-numbers': ('version1', 'version2'),
    'leetcode-166-fraction-to-recurring-decimal': ('numerator', 'denominator'),
    'leetcode-167-two-sum-ii-input-array-is-sorted': ('numbers', 'target'),
    'leetcode-168-excel-sheet-column-title': ('n',),
    'leetcode-17-letter-combinations-of-a-phone-number': ('digits',),
    'leetcode-171-excel-sheet-column-number': ('s',),
    'leetcode-172-factorial-trailing-zeroes': ('n',),
    'leetcode-174-dungeon-game': ('dungeon',),
    'leetcode-179-largest-number': ('nums',),
    'leetcode-18-4sum': ('nums', 'target'),
    'leetcode-187-repeated-dna-sequences': ('s',),
    'leetcode-188-best-time-to-buy-and-sell-stock-iv': ('k', 'prices'),
    'leetcode-189-rotate-array': ('nums', 'k'),
    'leetcode-19-remove-nth-node-from-end-of-list': ('head', 'n'),
    'leetcode-190-reverse-bits': ('n',),
    'leetcode-191-number-of-1-bits': ('n',),
    'leetcode-199-binary-tree-right-side-view': ('root',),
    'leetcode-2-add-two-numbers': ('l1', 'l2'),
    'leetcode-201-bitwise-and-of-numbers-range': ('m', 'n'),
    'leetcode-202-happy-number': ('n',),
    'leetcode-203-remove-linked-list-elements': ('head', 'val'),
    'leetcode-204-count-primes': ('n',),
    'leetcode-205-isomorphic-strings': ('s', 't'),
    'leetcode-206-reverse-linked-list': ('head',),
    'leetcode-21-merge-two-sorted-lists': ('list1', 'list2'),
    'leetcode-210-course-schedule-ii': ('numCourses', 'prerequisites'),
    'leetcode-213-house-robber-ii': ('nums',),
    'leetcode-214-shortest-palindrome': ('s',),
    'leetcode-215-kth-largest-element-in-an-array': ('nums', 'k'),
    'leetcode-218-the-skyline-problem': ('buildings',),
    'leetcode-219-contains-duplicate-ii': ('nums', 'k'),
    'leetcode-221-maximal-square': ('matrix',),
    'leetcode-222-count-complete-tree-nodes': ('root',),
    'leetcode-223-rectangle-area': ('A', 'B', 'C', 'D', 'E', 'F', 'G', 'H'),
    'leetcode-224-basic-calculator': ('s',),
    'leetcode-226-invert-binary-tree': ('root',),
    'leetcode-227-basic-calculator-ii': ('s',),
    'leetcode-228-summary-ranges': ('nums',),
    'leetcode-23-merge-k-sorted-lists': ('lists',),
    'leetcode-230-kth-smallest-element-in-a-bst': ('root', 'k'),
    'leetcode-231-power-of-two': ('n',),
    'leetcode-234-palindrome-linked-list': ('head',),
    'leetcode-235-lowest-common-ancestor-of-a-binary-search-tree': ('root', 'p', 'q'),
    'leetcode-236-lowest-common-ancestor-of-a-binary-tree': ('root', 'p', 'q'),
    'leetcode-239-sliding-window-maximum': ('nums', 'k'),
    'leetcode-24-swap-nodes-in-pairs': ('head',),
    'leetcode-240-search-a-2d-matrix-ii': ('matrix', 'target'),
    'leetcode-246-strobogrammatic-number': ('num',),
    'leetcode-249-group-shifted-strings': ('strings',),
    'leetcode-25-reverse-nodes-in-k-group': ('head', 'k'),
    'leetcode-252-meeting-rooms': ('intervals',),
    'leetcode-253-meeting-rooms-ii': ('intervals',),
    'leetcode-254-factor-combinations': ('n',),
    'leetcode-256-paint-house': ('costs',),
    'leetcode-258-add-digits': ('num',),
    'leetcode-259-3sum-smaller': ('nums', 'target'),
    'leetcode-26-remove-duplicates-from-sorted-array': ('nums',),
    'leetcode-261-graph-valid-tree': ('n', 'edges'),
    'leetcode-263-ugly-number': ('n',),
    'leetcode-265-paint-house-ii': ('costs',),
    'leetcode-267-palindrome-permutation-ii': ('s',),
    'leetcode-269-alien-dictionary': ('words',),
    'leetcode-27-remove-element': ('nums', 'val'),
    'leetcode-270-closest-binary-search-tree-value': ('root', 'target'),
    'leetcode-271-encode-and-decode-strings': ('strs',),
    'leetcode-273-integer-to-english-words': ('num',),
    'leetcode-274-h-index': ('citations',),
    'leetcode-275-h-index-ii': ('citations',),
    'leetcode-277-find-the-celebrity': ('n',),
    'leetcode-279-perfect-squares': ('n',),
    'leetcode-28-find-the-index-of-the-first-occurrence-in-a-string': ('haystack', 'needle'),
    'leetcode-285-inorder-successor-in-bst': ('root', 'p'),
    'leetcode-286-walls-and-gates': ('rooms',),
    'leetcode-287-find-the-duplicate-number': ('nums',),
    'leetcode-29-divide-two-integers': ('dividend', 'divisor'),
    'leetcode-290-word-pattern': ('pattern', 'str'),
    'leetcode-292-nim-game': ('n',),
    'leetcode-297-serialize-and-deserialize-binary-tree': ('root',),
    'leetcode-30-substring-with-concatenation-of-all-words': ('s', 'words'),
    'leetcode-301-remove-invalid-parentheses': ('s',),
    'leetcode-303-range-sum-query-immutable': ('left', 'right'),
    'leetcode-309-best-time-to-buy-and-sell-stock-with-cooldown': ('prices',),
    'leetcode-31-next-permutation': ('nums',),
    'leetcode-311-sparse-matrix-multiplication': ('mat1', 'mat2'),
    'leetcode-312-burst-balloons': ('nums',),
    'leetcode-314-binary-tree-vertical-order-traversal': ('root',),
    'leetcode-317-shortest-distance-from-all-buildings': ('grid',),
    'leetcode-32-longest-valid-parentheses': ('s',),
    'leetcode-323-number-of-connected-components-in-an-undirected-graph': ('n', 'edges'),
    'leetcode-325-maximum-size-subarray-sum-equals-k': ('nums', 'k'),
    'leetcode-328-odd-even-linked-list': ('head',),
    'leetcode-329-longest-increasing-path-in-a-matrix': ('matrix',),
    'leetcode-332-reconstruct-itinerary': ('tickets',),
    'leetcode-339-nested-list-weight-sum': ('nestedList',),
    'leetcode-34-find-first-and-last-position-of-element-in-sorted-array': ('nums', 'target'),
    'leetcode-340-longest-substring-with-at-most-k-distinct-characters': ('s', 'k'),
    'leetcode-343-integer-break': ('n',),
    'leetcode-345-reverse-vowels-of-a-string': ('s',),
    'leetcode-35-search-insert-position': ('nums', 'target'),
    'leetcode-354-russian-doll-envelopes': ('envelopes',),
    'leetcode-355-design-twitter': ('userId', 'tweetId'),
    'leetcode-36-valid-sudoku': ('board',),
    'leetcode-366-find-leaves-of-binary-tree': ('root',),
    'leetcode-367-valid-perfect-square': ('num',),
    'leetcode-368-largest-divisible-subset': ('nums',),
    'leetcode-37-sudoku-solver': ('board',),
    'leetcode-371-sum-of-two-integers': ('a', 'b'),
    'leetcode-377-combination-sum-iv': ('nums', 'target'),
    'leetcode-378-kth-smallest-element-in-a-sorted-matrix': ('matrix', 'k'),
    'leetcode-38-count-and-say': ('n',),
    'leetcode-385-mini-parser': ('s',),
    'leetcode-388-longest-absolute-file-path': ('input',),
    'leetcode-392-is-subsequence': ('s', 't'),
    'leetcode-394-decode-string': ('s',),
    'leetcode-399-evaluate-division': ('equations', 'values', 'queries'),
    'leetcode-4-median-of-two-sorted-arrays': ('nums1', 'nums2'),
    'leetcode-40-combination-sum-ii': ('candidates', 'target'),
    'leetcode-402-remove-k-digits': ('num', 'k'),
    'leetcode-406-queue-reconstruction-by-height': ('people',),
    'leetcode-408-valid-word-abbreviation': ('word', 'abbr'),
    'leetcode-41-first-missing-positive': ('nums',),
    'leetcode-410-split-array-largest-sum': ('nums', 'm'),
    'leetcode-415-add-strings': ('num1', 'num2'),
    'leetcode-416-partition-equal-subset-sum': ('nums',),
    'leetcode-417-pacific-atlantic-water-flow': ('heights',),
    'leetcode-42-trapping-rain-water': ('height',),
    'leetcode-426-convert-binary-search-tree-to-sorted-doubly-linked-list': ('root',),
    'leetcode-428-serialize-and-deserialize-n-ary-tree': ('root',),
    'leetcode-43-multiply-strings': ('num1', 'num2'),
    'leetcode-430-flatten-a-multilevel-doubly-linked-list': ('head',),
    'leetcode-433-minimum-genetic-mutation': ('start', 'end', 'bank'),
    'leetcode-435-non-overlapping-intervals': ('intervals',),
    'leetcode-437-path-sum-iii': ('root', 'summ'),
    'leetcode-44-wildcard-matching': ('s', 'p'),
    'leetcode-443-string-compression': ('chars',),
    'leetcode-448-find-all-numbers-disappeared-in-an-array': ('nums',),
    'leetcode-45-jump-game-ii': ('nums',),
    'leetcode-456-132-pattern': ('nums',),
    'leetcode-459-repeated-substring-pattern': ('s',),
    'leetcode-460-lfu-cache': ('key', 'value'),
    'leetcode-463-island-perimeter': ('grid',),
    'leetcode-468-validate-ip-address': ('IP',),
    'leetcode-47-permutations-ii': ('nums',),
    'leetcode-474-ones-and-zeroes': ('strs', 'm', 'n'),
    'leetcode-48-rotate-image': ('matrix',),
    'leetcode-480-sliding-window-median': ('nums', 'k'),
    'leetcode-494-target-sum': ('nums', 'target'),
    'leetcode-496-next-greater-element-i': ('nums1', 'nums2'),
    'leetcode-498-diagonal-traverse': ('matrix',),
    'leetcode-5-longest-palindromic-substring': ('s',),
    'leetcode-50-powx-n': ('x', 'n'),
    'leetcode-51-n-queens': ('n',),
    'leetcode-518-coin-change-ii': ('amount', 'coins'),
    'leetcode-52-n-queens-ii': ('n',),
    'leetcode-520-detect-capital': ('word',),
    'leetcode-523-continuous-subarray-sum': ('nums', 'k'),
    'leetcode-525-contiguous-array': ('nums',),
    'leetcode-532-k-diff-pairs-in-an-array': ('nums', 'k'),
    'leetcode-536-construct-binary-tree-from-string': ('s',),
    'leetcode-540-single-element-in-a-sorted-array': ('nums',),
    'leetcode-541-reverse-string-ii': ('s', 'k'),
    'leetcode-543-diameter-of-binary-tree': ('root',),
    'leetcode-545-boundary-of-binary-tree': ('root',),
    'leetcode-55-jump-game': ('nums',),
    'leetcode-560-subarray-sum-equals-k': ('nums', 'k'),
    'leetcode-567-permutation-in-string': ('s1', 's2'),
    'leetcode-572-subtree-of-another-tree': ('s', 't'),
    'leetcode-58-length-of-last-word': ('s',),
    'leetcode-59-spiral-matrix-ii': ('n',),
    'leetcode-6-zigzag-conversion': ('s', 'numRows'),
    'leetcode-60-permutation-sequence': ('n', 'k'),
    'leetcode-605-can-place-flowers': ('flowerbed', 'n'),
    'leetcode-606-construct-string-from-binary-tree': ('t',),
    'leetcode-61-rotate-list': ('head', 'k'),
    'leetcode-617-merge-two-binary-trees': ('root1', 'root2'),
    'leetcode-62-unique-paths': ('m', 'n'),
    'leetcode-621-task-scheduler': ('tasks', 'n'),
    'leetcode-628-maximum-product-of-three-numbers': ('nums',),
    'leetcode-63-unique-paths-ii': ('obstacleGrid',),
    'leetcode-630-course-schedule-iii': ('courses',),
    'leetcode-636-exclusive-time-of-functions': ('n', 'logs'),
    'leetcode-64-minimum-path-sum': ('grid',),
    'leetcode-643-maximum-average-subarray-i': ('nums', 'k'),
    'leetcode-645-set-mismatch': ('nums',),
    'leetcode-647-palindromic-substrings': ('s',),
    'leetcode-65-valid-number': ('s',),
    'leetcode-652-find-duplicate-subtrees': ('root',),
    'leetcode-658-find-k-closest-elements': ('arr', 'k', 'x'),
    'leetcode-66-plus-one': ('digits',),
    'leetcode-67-add-binary': ('a', 'b'),
    'leetcode-670-maximum-swap': ('num',),
    'leetcode-673-number-of-longest-increasing-subsequence': ('nums',),
    'leetcode-678-valid-parenthesis-string': ('s',),
    'leetcode-68-text-justification': ('words', 'maxWidth'),
    'leetcode-680-valid-palindrome-ii': ('s',),
    'leetcode-684-redundant-connection': ('edges',),
    'leetcode-686-repeated-string-match': ('a', 'b'),
    'leetcode-69-sqrtx': ('x',),
    'leetcode-690-employee-importance': ('employees', 'id'),
    'leetcode-695-max-area-of-island': ('grid',),
    'leetcode-697-degree-of-an-array': ('nums',),
    'leetcode-698-partition-to-k-equal-sum-subsets': ('nums', 'k'),
    'leetcode-7-reverse-integer': ('x',),
    'leetcode-708-insert-into-a-sorted-circular-linked-list': ('head', 'insertVal'),
    'leetcode-71-simplify-path': ('path',),
    'leetcode-713-subarray-product-less-than-k': ('nums', 'k'),
    'leetcode-714-best-time-to-buy-and-sell-stock-with-transaction-fee': ('prices', 'fee'),
    'leetcode-72-edit-distance': ('word1', 'word2'),
    'leetcode-720-longest-word-in-dictionary': ('words',),
    'leetcode-721-accounts-merge': ('accounts',),
    'leetcode-722-remove-comments': ('source',),
    'leetcode-724-find-pivot-index': ('nums',),
    'leetcode-729-my-calendar-i': ('start', 'end'),
    'leetcode-735-asteroid-collision': ('asteroids',),
    'leetcode-74-search-a-2d-matrix': ('matrix', 'target'),
    'leetcode-741-cherry-pickup': ('grid',),
    'leetcode-743-network-delay-time': ('times', 'n', 'k'),
    'leetcode-746-min-cost-climbing-stairs': ('cost',),
    'leetcode-75-sort-colors': ('nums',),
    'leetcode-76-minimum-window-substring': ('s', 't'),
    'leetcode-763-partition-labels': ('S',),
    'leetcode-77-combinations': ('n', 'k'),
    'leetcode-772-basic-calculator-iii': ('s',),
    'leetcode-778-swim-in-rising-water': ('grid',),
    'leetcode-784-letter-case-permutation': ('S',),
    'leetcode-787-cheapest-flights-within-k-stops': ('n', 'flights', 'src', 'dst', 'k'),
    'leetcode-79-word-search': ('board', 'word'),
    'leetcode-791-custom-sort-string': ('S', 'T'),
    'leetcode-796-rotate-string': ('A', 'B'),
    'leetcode-8-string-to-integer-atoi': ('s',),
    'leetcode-80-remove-duplicates-from-sorted-array-ii': ('nums',),
    'leetcode-81-search-in-rotated-sorted-array-ii': ('nums', 'target'),
    'leetcode-82-remove-duplicates-from-sorted-list-ii': ('head',),
    'leetcode-820-short-encoding-of-words': ('words',),
    'leetcode-824-goat-latin': ('S',),
    'leetcode-825-friends-of-appropriate-ages': ('ages',),
    'leetcode-827-making-a-large-island': ('grid',),
    'leetcode-83-remove-duplicates-from-sorted-list': ('head',),
    'leetcode-833-find-and-replace-in-string': ('s', 'indexes', 'sources', 'targets'),
    'leetcode-84-largest-rectangle-in-histogram': ('heights',),
    'leetcode-846-hand-of-straights': ('hand', 'W'),
    'leetcode-849-maximize-distance-to-closest-person': ('seats',),
    'leetcode-85-maximal-rectangle': ('matrix',),
    'leetcode-853-car-fleet': ('target', 'position', 'speed'),
    'leetcode-857-minimum-cost-to-hire-k-workers': ('quality', 'wage', 'k'),
    'leetcode-86-partition-list': ('head', 'x'),
    'leetcode-863-all-nodes-distance-k-in-binary-tree': ('root', 'target', 'K'),
    'leetcode-864-shortest-path-to-get-all-keys': ('grid',),
    'leetcode-867-transpose-matrix': ('A',),
    'leetcode-87-scramble-string': ('s1', 's2'),
    'leetcode-872-leaf-similar-trees': ('root1', 'root2'),
    'leetcode-88-merge-sorted-array': ('nums1', 'm', 'nums2', 'n'),
    'leetcode-89-gray-code': ('n',),
    'leetcode-9-palindrome-number': ('x',),
    'leetcode-90-subsets-ii': ('nums',),
    'leetcode-907-sum-of-subarray-minimums': ('arr',),
    'leetcode-909-snakes-and-ladders': ('board',),
    'leetcode-918-maximum-sum-circular-subarray': ('A',),
    'leetcode-92-reverse-linked-list-ii': ('head', 'left', 'right'),
    'leetcode-921-minimum-add-to-make-parentheses-valid': ('s',),
    'leetcode-93-restore-ip-addresses': ('s',),
    'leetcode-931-minimum-falling-path-sum': ('A',),
    'leetcode-934-shortest-bridge': ('grid',),
    'leetcode-935-knight-dialer': ('n',),
    'leetcode-938-range-sum-of-bst': ('root', 'L', 'R'),
    'leetcode-94-binary-tree-inorder-traversal': ('root',),
    'leetcode-95-unique-binary-search-trees-ii': ('n',),
    'leetcode-958-check-completeness-of-a-binary-tree': ('root',),
    'leetcode-96-unique-binary-search-trees': ('n',),
    'leetcode-966-vowel-spellchecker': ('wordlist', 'queries'),
    'leetcode-97-interleaving-string': ('s1', 's2', 's3'),
    'leetcode-973-k-closest-points-to-origin': ('points', 'K'),
    'leetcode-976-largest-perimeter-triangle': ('A',),
    'leetcode-977-squares-of-a-sorted-array': ('A',),
    'leetcode-98-validate-binary-search-tree': ('root',),
    'leetcode-986-interval-list-intersections': ('firstList', 'secondList'),
    'leetcode-987-vertical-order-traversal-of-a-binary-tree': ('root',),
    'leetcode-989-add-to-array-form-of-integer': ('num', 'k'),
    'leetcode-99-recover-binary-search-tree': ('root',),
    'leetcode-994-rotting-oranges': ('grid',),
    'leetcode-996-number-of-squareful-arrays': ('A',),
    'longest-increasing-subsequence': ('nums',),
    'longest-unique-substring': ('s',),
    'majority-element': ('nums',),
    'maximum-subarray': ('nums',),
    'merge-intervals': ('intervals',),
    'merge-sorted-arrays': ('nums1', 'nums2'),
    'minimum-size-subarray-sum': ('target', 'nums'),
    'missing-number': ('nums',),
    'move-zeroes': ('nums',),
    'number-of-islands': ('grid',),
    'permutations': ('nums',),
    'product-except-self': ('nums',),
    'ransom-note': ('ransomNote', 'magazine'),
    'reverse-words': ('s',),
    'rotate-matrix': ('matrix',),
    'search-rotated-array': ('nums', 'target'),
    'set-matrix-zeroes': ('matrix',),
    'shortest-unweighted-path': ('n', 'edges', 'source', 'target'),
    'single-number': ('nums',),
    'spiral-matrix': ('matrix',),
    'subsets': ('nums',),
    'three-sum': ('nums',),
    'top-k-frequent': ('nums', 'k'),
    'two-sum': ('nums', 'target'),
    'valid-anagram': ('s', 't'),
    'valid-palindrome': ('s',),
    'valid-parentheses': ('s',),
    'word-break': ('s', 'wordDict'),
}
